<a href="https://colab.research.google.com/github/alfonso-uacj/ColabFiles/blob/main/Practica4_al256111.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np #numpy para generar matrices

# Se crean dos matrices de 3x3 con números aleatorios entre 1 y 10
mat01 = np.random.randint(1, 10, size=(3, 3))
mat02 = np.random.randint(1, 10, size=(3, 3))

#sumar las dos matrices
mat_sum = mat01 + mat02

#Resta la segunda matriz de la primera.
mat_res = mat02 - mat01

#Multiplica la primera matriz por 2
mat_mul = mat01 * 2

#Realiza una multiplicación matricial entre las dos matrices.
mat_multiplicar = np.matmul(mat01, mat02) # se usa matmul para la operacion de multiplicar


#imprimir las matrices generadas para visibilidad
print("matriz 01")
print(mat01)
print("matriz 02")
print(mat02)
# imprimir la suma de matrices
print("Suma \n", mat_sum)
# imprimir la resta de matrices
print("Resta \n", mat_res)
# imprimir la primera matriz por 2
print("Primera multiplicada por dos \n", mat_mul)
# imprimir la multiplicacion de matrices
print("Multiplicacion \n", mat_multiplicar)

matriz 01
[[3 5 9]
 [7 1 9]
 [8 5 1]]
matriz 02
[[8 7 5]
 [5 5 1]
 [8 3 6]]
Suma 
 [[11 12 14]
 [12  6 10]
 [16  8  7]]
Resta 
 [[ 5  2 -4]
 [-2  4 -8]
 [ 0 -2  5]]
Primera multiplicada por dos 
 [[ 6 10 18]
 [14  2 18]
 [16 10  2]]
Multiplicacion 
 [[121  73  74]
 [133  81  90]
 [ 97  84  51]]


https://github.com/alfonso-uacj/ColabFiles/blob/main/Practica4_al256111.ipynb